# Generated by Django 3.2 on 2021-04-27 03:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rate', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('offer_price', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('base_price', models.FloatField(validators=[django.core.validators.DecimalValidator(18, 4)])),
                ('in_offer', models.BooleanField(default=False)),
                ('image', models.TextField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='status.state')),
            ],
        ),
    ]
